#This file should not be edited by Code-Snippets contributors. Any edits to this page will result in a rejected pull request.

name: Record event on devprogramresources
on:
  push:
    branches: main
  fork:
    branches: main
  issues:
    types: [opened, closed]
    branches: main
  pull_request_target:
    types: [opened, closed]
    branches: main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Log payload
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: Contact DPR
      id: myRequest
      uses: fjogeleit/http-request-action@v1.8.1
      with:
        url: 'https://devprogramresources.service-now.com/api/x_snc_code_snippet/code_snippets/event'
        method: 'POST'
        contentType: application/json
        data: ${{ toJson(github) }}
        username: ${{ secrets.DPRD_USERNAME }}
        password: ${{ secrets.DPRD_PASSWORD }}
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}
